traitCountDict = {
    "type": {
        "Normal": 100,
        "Light": 50,
        "Dark": 50,
        "Brown": 50,
        "Dark Brown": 30,
        "Black": 7,
        "Zombie": 5,
        "Devil": 3,
        "Alien": 5,
    },
    "body": {
        "Pink Shirt": 20,
        "Lime Shirt": 20,
        "White Shirt": 20,
        "Purple Shirt": 20,
        "Polka Dots": 20,
        "Vice Shirt": 20,
        "Lucky Shirt": 20,
        "Goku Shirt": 20,
        "Diaper": 20,
        "Black Suit": 20,
        "Navy Suit": 20,
        "Purple Suit": 20,
        "Nyan Doge": 20,
    },
    "neck": {
        "Blue Collar": 10,
        "Red Collar": 10,
        "Purple Bowtie": 10,
        "Green Bowtie": 10,
        "Yellow Bowtie": 10,
        "Orange Bowtie": 10,
        "Emerald Necklace": 3,
        "Sapphire Necklace": 2,
        "Ruby Necklace": 2,
        "Diamond Necklace": 1,
        "Red Scarf": 10,
        "Green Scarf": 10,
        "Cape": 7,
    },
    "mouth": {
        "Bone": 30,
        "Tongue Out": 30,
        "Joint": 30,
    },
    "hat": {
        "Party Hat": 10,
        "Blue Bandana": 10,
        "Dark Bandana": 10,
        "Red Tophat": 10,
        "Green Tophat": 10,
        "White Tophat": 10,
        "Pink Mohawk": 10,
        "Purple Mohawk": 10,
        "Wizard Hat": 10,
        "Crown": 10,
        "Fez": 10,
        "Jester Hat": 10,
        "Poop": 10,
        "Flowers": 10,
        "Headphones": 10,
    },
    "eyes":  {
        "Pit Vipers": 20,
        "Solana Shades": 10,
        "Vice Shades": 20,
        "Angry Eyebrows": 20,
        "Heart Eyes": 20,
        "Cyclops": 10,
        "Googley Eyes": 10,
        "Thug Lyfe": 20,
        "Glasses": 25,
    }
}