TRAIT_ENCODINGS = {
    "type": {
        "n": "Normal",
        "l": "Light",
        "d": "Dark",
        "b": "Brown",
        "r": "Dark Brown",
        "k": "Black",
        "z": "Zombie",
        "s": "Skeleton",
        "v": "Devil",
        "a": "Alien",
        "_": "None"
    },
    "body": {
        "p": "Pink Shirt",
        "l": "Lime Shirt",
        "w": "White Shirt",
        "r": "Purple Shirt",
        "h": "Dark Shirt",
        "e": "Striped Shirt",
        "d": "Polka Dots",
        "c": "Vice Shirt",
        "k": "Lucky Shirt",
        "o": "Goku Shirt",
        "i": "Diaper",
        "s": "Black Suit",
        "n": "Navy Suit",
        "t": "Purple Suit",
        "y": "Nyan Doge",
        "_": "None"
    },
    "neck": {
        "b": "Blue Collar",
        "c": "Red Collar",
        "k": "Pink Collar",
        "l": "Green Collar",
        "z": "Purple Collar",
        "r": "Purple Bowtie",
        "g": "Green Bowtie",
        "y": "Yellow Bowtie",
        "o": "Orange Bowtie",
        "e": "Emerald Necklace",
        "s": "Sapphire Necklace",
        "u": "Ruby Necklace",
        "d": "Diamond Necklace",
        "f": "Red Scarf",
        "n": "Green Scarf",
        "p": "Cape",
        "_": "None"
    },
    "mouth": {
        "b": "Bone",
        "t": "Tongue Out",
        "j": "Joint",
        "p": "Pipe",
        "c": "Chicken Bone",
        "d": "Diamond Bone",
        "v": "Vape",
        "_": "None"
    },
    "hat": {
        "p": "Party Hat",
        "b": "Blue Bandana",
        "n": "Dark Bandana",
        "r": "Red Tophat",
        "g": "Green Tophat",
        "w": "White Tophat",
        "q": "Dark Tophat",
        "m": "Pink Mohawk",
        "k": "Purple Mohawk",
        "z": "Wizard Hat",
        "c": "Crown",
        "f": "Fez",
        "j": "Jester Hat",
        "o": "Poop",
        "l": "Flowers",
        "h": "Headphones",
        "e": "Green Cap",
        "x": "Orange Cap",
        "y": "Red Cap",
        "u": "Blue Cap",
        "a": "Pink Cap",
        "v": "Purple Cap",
        "d": "Beer Hat",
        "t": "Santa Hat",
        "s": "Sombrero",
        "i": "Goku Hair",
        "_": "None"
    },
    "eyes": {
        "p": "Pit Vipers",
        "s": "Solana Shades",
        "c": "Vice Shades",
        "a": "Angry Eyebrows",
        "h": "Heart Eyes",
        "y": "Cyclops",
        "g": "Googley Eyes",
        "t": "Thug Lyfe",
        "n": "Glasses",
        "v": "Happy",
        "_": "None"
    }
}