traitCountDict = {
    "type": {
        "Normal": 1000,
        "Light": 500,
        "Dark": 500,
        "Brown": 500,
        "Dark Brown": 300,
        "Black": 70,
        "Zombie": 50,
        "Devil": 30,
        "Alien": 50,
    },
    "body": {
        "Pink Shirt": 300,
        "Lime Shirt": 300,
        "White Shirt": 300,
        "Purple Shirt": 300,
        "Polka Dots": 300,
        "Vice Shirt": 40,
        "Lucky Shirt": 50,
        "Goku Shirt": 30,
        "Diaper": 30,
        "Black Suit": 100,
        "Navy Suit": 80,
        "Purple Suit": 60,
        "Nyan Doge": 20,
    },
    "neck": {
        "Blue Collar": 100,
        "Red Collar": 100,
        "Purple Bowtie": 100,
        "Green Bowtie": 100,
        "Yellow Bowtie": 100,
        "Orange Bowtie": 100,
        "Emerald Necklace": 30,
        "Sapphire Necklace": 10,
        "Ruby Necklace": 10,
        "Diamond Necklace": 1,
        "Red Scarf": 100,
        "Green Scarf": 100,
        "Cape": 50,
    },
    "mouth": {
        "Bone": 300,
        "Tongue Out": 250,
        "Joint": 200,
    },
    "hat": {
        "Party Hat": 100,
        "Blue Bandana": 100,
        "Dark Bandana": 200,
        "Red Tophat": 200,
        "Green Tophat": 200,
        "White Tophat": 200,
        "Pink Mohawk": 100,
        "Purple Mohawk": 100,
        "Wizard Hat": 50,
        "Crown": 1,
        "Fez": 100,
        "Jester Hat": 75,
        "Poop": 150,
        "Flowers": 150,
        "Headphones": 200,
    },
    "eyes":  {
        "Pit Vipers": 50,
        "Solana Shades": 30,
        "Vice Shades": 100,
        "Angry Eyebrows": 100,
        "Heart Eyes": 100,
        "Cyclops": 5,
        "Googley Eyes": 75,
        "Thug Lyfe": 150,
        "Glasses": 150,
        "Happy": 150,
    }
}