TRAIT_ENCODINGS = {
    "type": {
        "n": "Normal",
        "l": "Light",
        "d": "Dark",
        "b": "Brown",
        "r": "Dark Brown",
        "k": "Black",
        "z": "Zombie",
        "s": "Skeleton",
        "v": "Devil",
        "a": "Alien",
        "t": "AstroDoge",
        "i": "DiamondDoge",
        "_": "None"
    },
    "body": {
        "s": "SolanaHoodie",
        "l": "BlackHoodie",
        "u": "BlueHoodie",
        "g": "GrayHoodie",
        "r": "RedCollaredShirt",
        "k": "SkyBlueCollaredShirt",
        "b": "BlueCollaredShirt",
        "i": "PinkCollaredShirt",
        "y": "YellowCollaredShirt",
        "a": "GreenCollaredShirt",
        "o": "RainbowShirt",
        "p": "PikaTail",
        "t": "Tutu",
        "e": "Referee",
        "c": "ConeOfShame",
        "n": "BitcoinShirt",
        "_": "None"
    },
    "neck": {
        "g": "GoldenCollar",
        "d": "SilverCollar",
        "r": "RastaCollar",
        "f": "FreedomCollar",
        "l": "LeatherCollar",
        "_": "None"
    },
    "mouth": {
        "g": "Bubblegum",
        "d": "Drool",
        "b": "Booger",
        "c": "ClownNose",
        "n": "Bacon",
        "m": "Money",
        "f": "FireBreath",
        "o": "Kazoo",
        "l": "Ball",
        "k": "Cookie",
        "e": "BeerBottle",
        "s": "Surprised",
        "h": "Blushing",
        "_": "None"
    },
    "hat": {
        "b": "Beanie",
        "f": "FastFood",
        "p": "Floppy",
        "w": "PinkBow",
        "r": "PurpleBow",
        "s": "SaiyanHair",
        "c": "Cowboy",
        "u": "UncleSam",
        "o": "Halo",
        "e": "GoldEarring",
        "t": "PirateHat",
        "i": "RobinHood",
        "a": "Safari",
        "h": "Afro",
        "m": "SmallCap",
        "d": "RiceHat",
        "l": "Plunger",
        "_": "None"
    },
    "eyes": {
        "s": "GoldenVipers",
        "m": "Monocle",
        "l": "LaserEyes",
        "e": "Solaneyes",
        "c": "ClassyGlasses",
        "y": "Crying",
        "h": "Laughing",
        "w": "Wink",
        "b": "BigShades",
        "_": "None"
    }
}