traitCountDict = {
    "type": {
        "Normal": 200,
        "Light": 200,
        "Dark": 200,
        "Brown": 150,
        "Dark Brown": 150,
        "Black": 100,
    },
    "body": {
        "SolanaHoodie": 25,
        "BlackHoodie": 55,
        "BlueHoodie": 55,
        "GrayHoodie": 55,
        "RedCollaredShirt": 55,
        "SkyBlueCollaredShirt": 55,
        "BlueCollaredShirt": 55,
        "PinkCollaredShirt": 55,
        "YellowCollaredShirt": 55,
        "GreenCollaredShirt": 55,
        "RainbowShirt": 55,
        "PikaTail": 55,
        "Tutu": 55,
        "Referee": 55,
        "ConeOfShame": 55,
        "BitcoinShirt": 55,
    },
    "neck": {
        "GoldenCollar": 35,
        "SilverCollar": 75,
        "RastaCollar": 80,
        "FreedomCollar": 80,
        "LeatherCollar": 100,
    },
    "mouth": {
        "Bubblegum": 50,
        "Drool": 50,
        "Booger": 50,
        "ClownNose": 50,
        "Bacon": 50,
        "Money": 50,
        "FireBreath": 50,
        "Kazoo": 50,
        "Ball": 50,
        "Cookie": 50,
        "BeerBottle": 50,
        "Surprised": 50,
        "Blushing": 50,
    },
    "hat": {
        "Beanie": 50,
        "FastFood": 50,
        "Floppy": 50,
        "PinkBow": 50,
        "PurpleBow": 50,
        "SaiyanHair": 30,
        "Cowboy": 45,
        "UncleSam": 50,
        "Halo": 30,
        "GoldEarring": 40,
        "PirateHat": 50,
        "RobinHood": 50,
        "Safari": 50,
        "Afro": 40,
        "SmallCap": 50,
        "RiceHat": 40,
        "Plunger": 40,
    },
    "eyes":  {
        "GoldenVipers": 25,
        "Monocle": 50,
        "LaserEyes": 50,
        "Solaneyes": 50,
        "ClassyGlasses": 50,
        "Crying": 50,
        "Laughing": 50,
        "Wink": 50,
        "BigShades": 50,
    }
}