from PIL import Image
from colors import colorsDict
from traitEncodings import TRAIT_ENCODINGS

def drawEyes(im, trait, type):
    imNew = Image.new('RGBA', (24, 24), (0, 0, 0, 0))

    typePrimaryColor = "typeNormal"
    if type == "l":
        typePrimaryColor = "typeLight"
    elif type == "d":
        typePrimaryColor = "typeDark"
    elif type == "b":
        typePrimaryColor = "typeBrown"
    elif type == "r":
        typePrimaryColor = "typeDarkBrown"
    elif type == "k":
        typePrimaryColor = "typeBlack"
    elif type == "z":
        typePrimaryColor = "typeZombie"
    elif type == "v":
        typePrimaryColor = "typeDevil"
    elif type == "a":
        typePrimaryColor = "typeAlien"

    decodedType = TRAIT_ENCODINGS["eyes"][trait]
    if decodedType == "Pit Vipers":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["pvGreen"])
        imNew.putpixel((9, 11), colorsDict["pvYellow"])
        imNew.putpixel((10, 11), colorsDict["pvOrange"])
        imNew.putpixel((11, 11), colorsDict["pvRed"])
        imNew.putpixel((12, 11), colorsDict["pvRed"])
        imNew.putpixel((13, 11), colorsDict["pvRed"])
        imNew.putpixel((14, 11), colorsDict["pvOrange"])
        imNew.putpixel((15, 11), colorsDict["pvYellow"])
        imNew.putpixel((16, 11), colorsDict["pvGreen"])
        imNew.putpixel((17, 11), colorsDict["pvBlue"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["pvBlue"])
        imNew.putpixel((8, 12), colorsDict["pvGreen"])
        imNew.putpixel((9, 12), colorsDict["pvYellow"])
        imNew.putpixel((10, 12), colorsDict["pvOrange"])
        imNew.putpixel((11, 12), colorsDict["pvRed"])
        imNew.putpixel((13, 12), colorsDict["pvRed"])
        imNew.putpixel((14, 12), colorsDict["pvOrange"])
        imNew.putpixel((15, 12), colorsDict["pvYellow"])
        imNew.putpixel((16, 12), colorsDict["pvGreen"])
        imNew.putpixel((17, 12), colorsDict["pvBlue"])

        imNew.putpixel((8, 13), colorsDict["pvGreen"])
        imNew.putpixel((9, 13), colorsDict["pvYellow"])
        imNew.putpixel((10, 13), colorsDict["pvOrange"])
        imNew.putpixel((11, 13), colorsDict["pvRed"])
        imNew.putpixel((13, 13), colorsDict["pvRed"])
        imNew.putpixel((14, 13), colorsDict["pvOrange"])
        imNew.putpixel((15, 13), colorsDict["pvYellow"])
        imNew.putpixel((16, 13), colorsDict["pvGreen"])

    elif decodedType == "Happy":
        imNew.putpixel((9, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["black"])

        imNew.putpixel((8, 12), colorsDict["black"])
        imNew.putpixel((9, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((9, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((14, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 13), colorsDict[typePrimaryColor])
    elif decodedType == "Solana Shades":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["solanaShades5"])
        imNew.putpixel((9, 11), colorsDict["solanaShades4"])
        imNew.putpixel((10, 11), colorsDict["solanaShades3"])
        imNew.putpixel((11, 11), colorsDict["solanaShades2"])
        imNew.putpixel((12, 11), colorsDict["solanaShades1"])
        imNew.putpixel((13, 11), colorsDict["solanaShades2"])
        imNew.putpixel((14, 11), colorsDict["solanaShades3"])
        imNew.putpixel((15, 11), colorsDict["solanaShades4"])
        imNew.putpixel((16, 11), colorsDict["solanaShades5"])
        imNew.putpixel((17, 11), colorsDict["solanaShades6"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["solanaShades6"])
        imNew.putpixel((8, 12), colorsDict["solanaShades5"])
        imNew.putpixel((9, 12), colorsDict["solanaShades4"])
        imNew.putpixel((10, 12), colorsDict["solanaShades3"])
        imNew.putpixel((11, 12), colorsDict["solanaShades2"])
        imNew.putpixel((12, 12), colorsDict["solanaShades1"])
        imNew.putpixel((13, 12), colorsDict["solanaShades2"])
        imNew.putpixel((14, 12), colorsDict["solanaShades3"])
        imNew.putpixel((15, 12), colorsDict["solanaShades4"])
        imNew.putpixel((16, 12), colorsDict["solanaShades5"])
        imNew.putpixel((17, 12), colorsDict["solanaShades6"])

        imNew.putpixel((8, 13), colorsDict["solanaShades5"])
        imNew.putpixel((9, 13), colorsDict["solanaShades4"])
        imNew.putpixel((10, 13), colorsDict["solanaShades3"])
        imNew.putpixel((11, 13), colorsDict["solanaShades2"])
        imNew.putpixel((13, 13), colorsDict["solanaShades2"])
        imNew.putpixel((14, 13), colorsDict["solanaShades3"])
        imNew.putpixel((15, 13), colorsDict["solanaShades4"])
        imNew.putpixel((16, 13), colorsDict["solanaShades5"])

    elif decodedType == "Vice Shades":

        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["viceBrown"])
        imNew.putpixel((9, 11), colorsDict["viceBrown"])
        imNew.putpixel((10, 11), colorsDict["viceBrown"])
        imNew.putpixel((11, 11), colorsDict["viceBrown"])
        imNew.putpixel((12, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["viceBrown"])
        imNew.putpixel((14, 11), colorsDict["viceBrown"])
        imNew.putpixel((15, 11), colorsDict["viceBrown"])
        imNew.putpixel((16, 11), colorsDict["viceBrown"])
        imNew.putpixel((17, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((9, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((10, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((11, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((15, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((16, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((17, 12), colorsDict["black"])

        imNew.putpixel((7, 13), colorsDict["black"])
        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((10, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])
        imNew.putpixel((16, 13), colorsDict["black"])
        imNew.putpixel((17, 13), colorsDict["black"])

    elif decodedType == "Thug Lyfe":

        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])

        imNew.putpixel((6, 11), colorsDict["black"])
        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["black"])
        imNew.putpixel((9, 11), colorsDict["black"])
        imNew.putpixel((10, 11), colorsDict["white"])
        imNew.putpixel((11, 11), colorsDict["black"])
        imNew.putpixel((12, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["black"])
        imNew.putpixel((15, 11), colorsDict["black"])
        imNew.putpixel((16, 11), colorsDict["white"])
        imNew.putpixel((17, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["black"])
        imNew.putpixel((9, 12), colorsDict["white"])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((12, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["black"])
        imNew.putpixel((15, 12), colorsDict["white"])
        imNew.putpixel((16, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((13, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])

    elif decodedType == "Glasses":

        imNew.putpixel((6, 9), colorsDict["black"])
        imNew.putpixel((7, 9), colorsDict["black"])
        imNew.putpixel((8, 9), colorsDict["black"])
        imNew.putpixel((9, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["black"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((13, 9), colorsDict["black"])
        imNew.putpixel((14, 9), colorsDict["black"])
        imNew.putpixel((15, 9), colorsDict["black"])
        imNew.putpixel((16, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["black"])

        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["glasses"])
        imNew.putpixel((7, 10), colorsDict["glassesLight"])
        imNew.putpixel((8, 10), colorsDict["glasses"])
        imNew.putpixel((9, 10), colorsDict["glasses"])
        imNew.putpixel((10, 10), colorsDict["glasses"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["glasses"])
        imNew.putpixel((14, 10), colorsDict["glassesLight"])
        imNew.putpixel((15, 10), colorsDict["glasses"])
        imNew.putpixel((16, 10), colorsDict["glasses"])
        imNew.putpixel((17, 10), colorsDict["glasses"])
        imNew.putpixel((18, 10), colorsDict["black"])

        imNew.putpixel((5, 11), colorsDict["black"])
        imNew.putpixel((6, 11), colorsDict["glassesLight"])
        imNew.putpixel((7, 11), colorsDict["glasses"])
        imNew.putpixel((8, 11), colorsDict["glasses"])
        imNew.putpixel((9, 11), colorsDict["glasses"])
        imNew.putpixel((10, 11), colorsDict["glasses"])
        imNew.putpixel((11, 11), colorsDict["black"])
        imNew.putpixel((12, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["glassesLight"])
        imNew.putpixel((14, 11), colorsDict["glasses"])
        imNew.putpixel((15, 11), colorsDict["glasses"])
        imNew.putpixel((16, 11), colorsDict["glasses"])
        imNew.putpixel((17, 11), colorsDict["glasses"])
        imNew.putpixel((18, 11), colorsDict["black"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["glasses"])
        imNew.putpixel((7, 12), colorsDict["glasses"])
        imNew.putpixel((8, 12), colorsDict["glasses"])
        imNew.putpixel((9, 12), colorsDict["glasses"])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["glasses"])
        imNew.putpixel((15, 12), colorsDict["glasses"])
        imNew.putpixel((16, 12), colorsDict["glasses"])
        imNew.putpixel((17, 12), colorsDict["glasses"])
        imNew.putpixel((18, 12), colorsDict["black"])

        imNew.putpixel((6, 13), colorsDict["black"])
        imNew.putpixel((7, 13), colorsDict["black"])
        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])
        imNew.putpixel((16, 13), colorsDict["black"])
        imNew.putpixel((17, 13), colorsDict["black"])

    elif decodedType == "Angry Eyebrows":

        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])

        imNew.putpixel((10, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])

    elif decodedType == "Heart Eyes":

        imNew.putpixel((8, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 10), colorsDict["heartEyesRed"])

        imNew.putpixel((7, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((8, 11), colorsDict["white"])
        imNew.putpixel((9, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((11, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((12, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 11), colorsDict["white"])
        imNew.putpixel((14, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((16, 11), colorsDict["heartEyesRed"])

        imNew.putpixel((7, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((8, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((9, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((11, 12), colorsDict["heartEyesRedShade"])
        imNew.putpixel((12, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((14, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((16, 12), colorsDict["heartEyesRedShade"])

        imNew.putpixel((8, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((9, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 13), colorsDict["heartEyesRedShade"])
        imNew.putpixel((13, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((14, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 13), colorsDict["heartEyesRedShade"])

        imNew.putpixel((9, 14), colorsDict["heartEyesRedShade"])
        imNew.putpixel((14, 14), colorsDict["heartEyesRedShade"])

    elif decodedType == "Cyclops":

        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])

        imNew.putpixel((5, 11), colorsDict["black"])
        imNew.putpixel((6, 11), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((9, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((10, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((11, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((12, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((13, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((14, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((15, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((16, 11), colorsDict["black"])

        imNew.putpixel((4, 12), colorsDict["black"])
        imNew.putpixel((5, 12), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((6, 12), colorsDict["cyclopsYellow"])
        imNew.putpixel((7, 12), colorsDict["cyclopsYellow"])
        imNew.putpixel((8, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((9, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((10, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((11, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((12, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((13, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((14, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((15, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((16, 12), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((17, 12), colorsDict["black"])

        imNew.putpixel((5, 13), colorsDict["black"])
        imNew.putpixel((6, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((7, 13), colorsDict["black"])
        imNew.putpixel((8, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((9, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((10, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((11, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((12, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((13, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((14, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((15, 13), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((16, 13), colorsDict["black"])

        imNew.putpixel((6, 14), colorsDict["black"])
        imNew.putpixel((8, 14), colorsDict["black"])
        imNew.putpixel((9, 14), colorsDict["black"])
        imNew.putpixel((10, 14), colorsDict["black"])
        imNew.putpixel((11, 14), colorsDict["black"])
        imNew.putpixel((12, 14), colorsDict["black"])
        imNew.putpixel((13, 14), colorsDict["black"])
        imNew.putpixel((14, 14), colorsDict["black"])
        imNew.putpixel((15, 14), colorsDict["black"])

    elif decodedType == "Googley Eyes":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["black"])
        imNew.putpixel((9, 11), colorsDict["white"])
        imNew.putpixel((10, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["white"])
        imNew.putpixel((15, 11), colorsDict["white"])
        imNew.putpixel((16, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["white"])
        imNew.putpixel((9, 12), colorsDict["white"])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["white"])
        imNew.putpixel((15, 12), colorsDict["black"])
        imNew.putpixel((16, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])

    im.paste(imNew, (0,0), mask=imNew)
