from PIL import Image
from colors import colorsDict
from traitEncodings import TRAIT_ENCODINGS
from draw.drawBandana import drawBandana
from draw.drawTophat import drawTophat
from draw.drawCap import drawCap

def drawHat(im, trait):
    imNew = Image.new('RGBA', (24, 24), (0, 0, 0, 0))

    decodedType = TRAIT_ENCODINGS["hat"][trait]
    if decodedType == "Party Hat":

        imNew.putpixel((7, 1), colorsDict["partyHatStreamers"])
        imNew.putpixel((8, 1), colorsDict["partyHatStreamers"])
        imNew.putpixel((10, 1), colorsDict["partyHatStreamers"])
        imNew.putpixel((11, 1), colorsDict["partyHatStreamers"])
        imNew.putpixel((12, 1), colorsDict["partyHatStreamers"])

        imNew.putpixel((6, 2), colorsDict["partyHatStreamers"])
        imNew.putpixel((9, 2), colorsDict["partyHatStreamers"])
        imNew.putpixel((10, 2), colorsDict["partyHatStreamers"])

        imNew.putpixel((8, 3), colorsDict["partyHatStreamers"])
        imNew.putpixel((9, 3), colorsDict["partyHatStreamers"])
        imNew.putpixel((10, 3), colorsDict["partyHatOrange"])

        imNew.putpixel((7, 4), colorsDict["partyHatStreamers"])
        imNew.putpixel((9, 4), colorsDict["partyHatOrangeShade"])
        imNew.putpixel((10, 4), colorsDict["partyHatOrange"])
        imNew.putpixel((11, 4), colorsDict["partyHatOrange"])

        imNew.putpixel((9, 5), colorsDict["partyHatRedShade"])
        imNew.putpixel((10, 5), colorsDict["partyHatRed"])
        imNew.putpixel((11, 5), colorsDict["partyHatRed"])
        imNew.putpixel((12, 5), colorsDict["partyHatRed"])

        imNew.putpixel((9, 6), colorsDict["partyHatOrangeShade"])
        imNew.putpixel((10, 6), colorsDict["partyHatOrange"])
        imNew.putpixel((11, 6), colorsDict["partyHatOrange"])
        imNew.putpixel((12, 6), colorsDict["partyHatOrange"])
        imNew.putpixel((13, 6), colorsDict["partyHatOrange"])

        imNew.putpixel((9, 7), colorsDict["partyHatOrangeShade"])
        imNew.putpixel((10, 7), colorsDict["partyHatOrange"])
        imNew.putpixel((11, 7), colorsDict["partyHatOrange"])
        imNew.putpixel((12, 7), colorsDict["partyHatOrange"])
        imNew.putpixel((13, 7), colorsDict["partyHatRed"])
        imNew.putpixel((14, 7), colorsDict["partyHatRed"])

        imNew.putpixel((9, 8), colorsDict["partyHatRedShade"])
        imNew.putpixel((10, 8), colorsDict["partyHatRed"])
        imNew.putpixel((11, 8), colorsDict["partyHatRed"])
        imNew.putpixel((12, 8), colorsDict["partyHatRed"])
        imNew.putpixel((13, 8), colorsDict["partyHatRed"])
        imNew.putpixel((14, 8), colorsDict["partyHatRed"])

        imNew.putpixel((9, 9), colorsDict["partyHatRedShade"])
        imNew.putpixel((10, 9), colorsDict["partyHatRed"])
        imNew.putpixel((11, 9), colorsDict["partyHatRed"])
        imNew.putpixel((12, 9), colorsDict["partyHatRed"])
    elif decodedType == "Blue Bandana":
        drawBandana(imNew, "blue")
    elif decodedType == "Dark Bandana":
        drawBandana(imNew, "dark")
    elif decodedType == "Red Tophat":
        drawTophat(imNew, "redTophat", "redTophatShade", "redTophatStrap", "redTophatStrapShade", "redTophatBuckle")
    elif decodedType == "Green Tophat":
        drawTophat(imNew, "greenTophat", "greenTophatShade", "greenTophatStrap", "greenTophatStrapShade", "greenTophatBuckle")
    elif decodedType == "White Tophat":
        drawTophat(imNew, "whiteTophat", "whiteTophatShade", "whiteTophatStrap", "whiteTophatStrapShade", "whiteTophatBuckle")
    elif decodedType == "Dark Tophat":
        drawTophat(imNew, "darkTopHat", "darkTopHatShade", "whiteTophatStrap", "whiteTophatStrapShade", "whiteTophatBuckle")
    elif decodedType == "Green Cap":
        primaryColor = "greenCap1"
        shadeColor1 = "greenCap2"
        shadeColor2 = "greenCap3"
        drawCap(imNew, primaryColor, shadeColor1, shadeColor2)
    elif decodedType == "Orange Cap":
        primaryColor = "orangeCap1"
        shadeColor1 = "orangeCap2"
        shadeColor2 = "orangeCap3"
        drawCap(imNew, primaryColor, shadeColor1, shadeColor2)
    elif decodedType == "Red Cap":
        primaryColor = "redCap1"
        shadeColor1 = "redCap2"
        shadeColor2 = "redCap3"
        drawCap(imNew, primaryColor, shadeColor1, shadeColor2)
    elif decodedType == "Blue Cap":
        primaryColor = "blueCap1"
        shadeColor1 = "blueCap2"
        shadeColor2 = "blueCap3"
        drawCap(imNew, primaryColor, shadeColor1, shadeColor2)
    elif decodedType == "Pink Cap":
        primaryColor = "pinkCap1"
        shadeColor1 = "pinkCap2"
        shadeColor2 = "pinkCap3"
        drawCap(imNew, primaryColor, shadeColor1, shadeColor2)
    elif decodedType == "Flowers":
        imNew.putpixel((4, 4), colorsDict["flowers1"])
        imNew.putpixel((6, 4), colorsDict["flowers1"])

        imNew.putpixel((5, 5), colorsDict["flowers2"])
        imNew.putpixel((12, 5), colorsDict["flowers1"])
        imNew.putpixel((14, 5), colorsDict["flowers3"])
        imNew.putpixel((16, 5), colorsDict["flowers3"])

        imNew.putpixel((4, 6), colorsDict["flowers1"])
        imNew.putpixel((6, 6), colorsDict["flowers1"])
        imNew.putpixel((9, 6), colorsDict["flowers2"])
        imNew.putpixel((11, 6), colorsDict["flowers1"])
        imNew.putpixel((12, 6), colorsDict["flowers2"])
        imNew.putpixel((13, 6), colorsDict["flowers1"])
        imNew.putpixel((15, 6), colorsDict["flowers1"])

        imNew.putpixel((8, 7), colorsDict["flowers2"])
        imNew.putpixel((9, 7), colorsDict["flowers1"])
        imNew.putpixel((10, 7), colorsDict["flowers2"])
        imNew.putpixel((12, 7), colorsDict["flowers1"])
        imNew.putpixel((14, 7), colorsDict["flowers3"])
        imNew.putpixel((16, 7), colorsDict["flowers3"])

        imNew.putpixel((9, 8), colorsDict["flowers2"])
    elif decodedType == "Pink Mohawk":
        imNew.putpixel((13, 4), colorsDict["black"])

        imNew.putpixel((12, 5), colorsDict["black"])
        imNew.putpixel((13, 5), colorsDict["pinkMohawk"])
        imNew.putpixel((14, 5), colorsDict["black"])

        imNew.putpixel((11, 6), colorsDict["black"])
        imNew.putpixel((12, 6), colorsDict["pinkMohawk"])
        imNew.putpixel((13, 6), colorsDict["pinkMohawk"])
        imNew.putpixel((14, 6), colorsDict["black"])

        imNew.putpixel((10, 7), colorsDict["black"])
        imNew.putpixel((11, 7), colorsDict["pinkMohawkShade"])
        imNew.putpixel((12, 7), colorsDict["pinkMohawk"])
        imNew.putpixel((13, 7), colorsDict["pinkMohawk"])
        imNew.putpixel((14, 7), colorsDict["black"])

        imNew.putpixel((9, 8), colorsDict["black"])
        imNew.putpixel((10, 8), colorsDict["pinkMohawkShade"])
        imNew.putpixel((11, 8), colorsDict["pinkMohawk"])
        imNew.putpixel((12, 8), colorsDict["pinkMohawk"])
        imNew.putpixel((13, 8), colorsDict["pinkMohawk"])
        imNew.putpixel((14, 8), colorsDict["black"])

        imNew.putpixel((12, 9), colorsDict["pinkMohawk"])
        imNew.putpixel((13, 9), colorsDict["pinkMohawk"])

        imNew.putpixel((13, 10), colorsDict["pinkMohawk"])
    elif decodedType == "Purple Mohawk":
        imNew.putpixel((13, 4), colorsDict["black"])

        imNew.putpixel((12, 5), colorsDict["black"])
        imNew.putpixel((13, 5), colorsDict["purpleMohawk"])
        imNew.putpixel((14, 5), colorsDict["black"])

        imNew.putpixel((11, 6), colorsDict["black"])
        imNew.putpixel((12, 6), colorsDict["purpleMohawk"])
        imNew.putpixel((13, 6), colorsDict["purpleMohawk"])
        imNew.putpixel((14, 6), colorsDict["black"])

        imNew.putpixel((10, 7), colorsDict["black"])
        imNew.putpixel((11, 7), colorsDict["purpleMohawkShade"])
        imNew.putpixel((12, 7), colorsDict["purpleMohawk"])
        imNew.putpixel((13, 7), colorsDict["purpleMohawk"])
        imNew.putpixel((14, 7), colorsDict["black"])

        imNew.putpixel((9, 8), colorsDict["black"])
        imNew.putpixel((10, 8), colorsDict["purpleMohawkShade"])
        imNew.putpixel((11, 8), colorsDict["purpleMohawk"])
        imNew.putpixel((12, 8), colorsDict["purpleMohawk"])
        imNew.putpixel((13, 8), colorsDict["purpleMohawk"])
        imNew.putpixel((14, 8), colorsDict["black"])

        imNew.putpixel((12, 9), colorsDict["purpleMohawk"])
        imNew.putpixel((13, 9), colorsDict["purpleMohawk"])

        imNew.putpixel((13, 10), colorsDict["purpleMohawk"])
    elif decodedType == "Poop":
        imNew.putpixel((7, 0), colorsDict["black"])

        imNew.putpixel((12, 1), colorsDict["poopEdge"])
        imNew.putpixel((17, 1), colorsDict["black"])

        imNew.putpixel((9, 2), colorsDict["poopEdge"])
        imNew.putpixel((10, 2), colorsDict["poopEdge"])
        imNew.putpixel((11, 2), colorsDict["poopEdge"])
        imNew.putpixel((12, 2), colorsDict["poopShade"])
        imNew.putpixel((13, 2), colorsDict["poopEdge"])

        imNew.putpixel((2, 3), colorsDict["black"])
        imNew.putpixel((8, 3), colorsDict["poopEdge"])
        imNew.putpixel((9, 3), colorsDict["poopShade"])
        imNew.putpixel((10, 3), colorsDict["poop"])
        imNew.putpixel((11, 3), colorsDict["poop"])
        imNew.putpixel((12, 3), colorsDict["poopEdge"])
        imNew.putpixel((13, 3), colorsDict["poopEdge"])

        imNew.putpixel((9, 4), colorsDict["poopEdge"])
        imNew.putpixel((10, 4), colorsDict["poopShade"])
        imNew.putpixel((11, 4), colorsDict["poop"])
        imNew.putpixel((12, 4), colorsDict["poop"])
        imNew.putpixel((13, 4), colorsDict["poop"])
        imNew.putpixel((14, 4), colorsDict["poopEdge"])

        imNew.putpixel((8, 5), colorsDict["poopEdge"])
        imNew.putpixel((9, 5), colorsDict["poopEdge"])
        imNew.putpixel((10, 5), colorsDict["poopEdge"])
        imNew.putpixel((11, 5), colorsDict["poopEdge"])
        imNew.putpixel((12, 5), colorsDict["poopEdge"])
        imNew.putpixel((13, 5), colorsDict["black"])
        imNew.putpixel((14, 5), colorsDict["poopEdge"])
        imNew.putpixel((15, 5), colorsDict["poopEdge"])

        imNew.putpixel((7, 6), colorsDict["poopEdge"])
        imNew.putpixel((8, 6), colorsDict["poopShade"])
        imNew.putpixel((9, 6), colorsDict["poop"])
        imNew.putpixel((10, 6), colorsDict["poop"])
        imNew.putpixel((11, 6), colorsDict["poop"])
        imNew.putpixel((12, 6), colorsDict["poop"])
        imNew.putpixel((13, 6), colorsDict["poop"])
        imNew.putpixel((14, 6), colorsDict["poop"])
        imNew.putpixel((15, 6), colorsDict["poop"])
        imNew.putpixel((16, 6), colorsDict["poopEdge"])

        imNew.putpixel((8, 7), colorsDict["poopEdge"])
        imNew.putpixel((9, 7), colorsDict["poopEdge"])
        imNew.putpixel((10, 7), colorsDict["poopEdge"])
        imNew.putpixel((11, 7), colorsDict["poopEdge"])
        imNew.putpixel((12, 7), colorsDict["poopEdge"])
        imNew.putpixel((13, 7), colorsDict["poopEdge"])
        imNew.putpixel((14, 7), colorsDict["poopEdge"])
        imNew.putpixel((15, 7), colorsDict["poopEdge"])
    elif decodedType == "Headphones":
        imNew.putpixel((9, 2), colorsDict["black"])
        imNew.putpixel((10, 2), colorsDict["black"])
        imNew.putpixel((11, 2), colorsDict["black"])
        imNew.putpixel((12, 2), colorsDict["black"])
        imNew.putpixel((13, 2), colorsDict["black"])
        imNew.putpixel((14, 2), colorsDict["black"])

        imNew.putpixel((7, 3), colorsDict["black"])
        imNew.putpixel((8, 3), colorsDict["black"])
        imNew.putpixel((9, 3), colorsDict["headphonesStrapShade"])
        imNew.putpixel((10, 3), colorsDict["headphonesStrapShade"])
        imNew.putpixel((11, 3), colorsDict["headphonesStrap"])
        imNew.putpixel((12, 3), colorsDict["headphonesStrap"])
        imNew.putpixel((13, 3), colorsDict["headphonesStrap"])
        imNew.putpixel((14, 3), colorsDict["headphonesStrap"])
        imNew.putpixel((15, 3), colorsDict["black"])
        imNew.putpixel((16, 3), colorsDict["black"])

        imNew.putpixel((6, 4), colorsDict["black"])
        imNew.putpixel((7, 4), colorsDict["headphonesStrapShade"])
        imNew.putpixel((8, 4), colorsDict["headphonesStrap"])
        imNew.putpixel((9, 4), colorsDict["black"])
        imNew.putpixel((10, 4), colorsDict["black"])
        imNew.putpixel((11, 4), colorsDict["black"])
        imNew.putpixel((12, 4), colorsDict["black"])
        imNew.putpixel((13, 4), colorsDict["black"])
        imNew.putpixel((14, 4), colorsDict["black"])
        imNew.putpixel((15, 4), colorsDict["headphonesStrap"])
        imNew.putpixel((16, 4), colorsDict["headphonesStrap"])
        imNew.putpixel((17, 4), colorsDict["black"])

        imNew.putpixel((5, 5), colorsDict["black"])
        imNew.putpixel((6, 5), colorsDict["headphonesStrapShade"])
        imNew.putpixel((7, 5), colorsDict["black"])
        imNew.putpixel((8, 5), colorsDict["black"])
        imNew.putpixel((15, 5), colorsDict["black"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((17, 5), colorsDict["headphonesStrap"])
        imNew.putpixel((18, 5), colorsDict["black"])

        imNew.putpixel((5, 6), colorsDict["black"])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["black"])

        imNew.putpixel((1, 7), colorsDict["black"])
        imNew.putpixel((5, 7), colorsDict["black"])
        imNew.putpixel((6, 7), colorsDict["black"])
        imNew.putpixel((17, 7), colorsDict["black"])
        imNew.putpixel((18, 7), colorsDict["black"])
        imNew.putpixel((22, 7), colorsDict["black"])

        imNew.putpixel((2, 8), colorsDict["black"])
        imNew.putpixel((4, 8), colorsDict["black"])
        imNew.putpixel((5, 8), colorsDict["headphonesEar"])
        imNew.putpixel((6, 8), colorsDict["black"])
        imNew.putpixel((17, 8), colorsDict["black"])
        imNew.putpixel((18, 8), colorsDict["headphonesEar"])
        imNew.putpixel((19, 8), colorsDict["black"])
        imNew.putpixel((21, 8), colorsDict["black"])

        imNew.putpixel((4, 9), colorsDict["black"])
        imNew.putpixel((5, 9), colorsDict["headphonesEarShade"])
        imNew.putpixel((6, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["black"])
        imNew.putpixel((18, 9), colorsDict["headphonesEarShade"])
        imNew.putpixel((19, 9), colorsDict["black"])

        imNew.putpixel((2, 10), colorsDict["black"])
        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["headphonesEarShade"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])
        imNew.putpixel((18, 10), colorsDict["headphonesEarShade"])
        imNew.putpixel((19, 10), colorsDict["black"])
        imNew.putpixel((21, 10), colorsDict["black"])

        imNew.putpixel((1, 11), colorsDict["black"])
        imNew.putpixel((22, 11), colorsDict["black"])
    elif decodedType == "Wizard Hat":
        imNew.putpixel((8, 0), colorsDict["black"])
        imNew.putpixel((9, 0), colorsDict["black"])
        imNew.putpixel((10, 0), colorsDict["black"])
        imNew.putpixel((11, 0), colorsDict["black"])

        imNew.putpixel((5, 1), colorsDict["black"])
        imNew.putpixel((6, 1), colorsDict["black"])
        imNew.putpixel((7, 1), colorsDict["black"])
        imNew.putpixel((8, 1), colorsDict["wizardStar"])
        imNew.putpixel((9, 1), colorsDict["wizardPurple"])
        imNew.putpixel((10, 1), colorsDict["wizardPurple"])
        imNew.putpixel((11, 1), colorsDict["wizardPurple"])
        imNew.putpixel((12, 1), colorsDict["black"])

        imNew.putpixel((4, 2), colorsDict["black"])
        imNew.putpixel((5, 2), colorsDict["wizardPurple"])
        imNew.putpixel((6, 2), colorsDict["wizardPurple"])
        imNew.putpixel((7, 2), colorsDict["wizardPurple"])
        imNew.putpixel((8, 2), colorsDict["wizardPurple"])
        imNew.putpixel((9, 2), colorsDict["wizardPurpleShade"])
        imNew.putpixel((10, 2), colorsDict["wizardPurple"])
        imNew.putpixel((11, 2), colorsDict["wizardPurple"])
        imNew.putpixel((12, 2), colorsDict["wizardStar"])
        imNew.putpixel((13, 2), colorsDict["black"])

        imNew.putpixel((4, 3), colorsDict["black"])
        imNew.putpixel((5, 3), colorsDict["black"])
        imNew.putpixel((6, 3), colorsDict["black"])
        imNew.putpixel((7, 3), colorsDict["black"])
        imNew.putpixel((8, 3), colorsDict["black"])
        imNew.putpixel((9, 3), colorsDict["wizardPurpleShade"])
        imNew.putpixel((10, 3), colorsDict["wizardPurple"])
        imNew.putpixel((11, 3), colorsDict["wizardPurple"])
        imNew.putpixel((12, 3), colorsDict["wizardPurple"])
        imNew.putpixel((13, 3), colorsDict["wizardPurple"])
        imNew.putpixel((14, 3), colorsDict["black"])

        imNew.putpixel((4, 4), colorsDict["black"])
        imNew.putpixel((5, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((6, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((7, 4), colorsDict["black"])
        imNew.putpixel((8, 4), colorsDict["wizardPurpleShade"])
        imNew.putpixel((9, 4), colorsDict["wizardPurple"])
        imNew.putpixel((10, 4), colorsDict["wizardPurple"])
        imNew.putpixel((11, 4), colorsDict["wizardPurple"])
        imNew.putpixel((12, 4), colorsDict["wizardPurple"])
        imNew.putpixel((13, 4), colorsDict["wizardPurple"])
        imNew.putpixel((14, 4), colorsDict["wizardPurple"])
        imNew.putpixel((15, 4), colorsDict["black"])
        imNew.putpixel((16, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((17, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((18, 4), colorsDict["solanaBand"][4])

        imNew.putpixel((3, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((6, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((7, 5), colorsDict["black"])
        imNew.putpixel((8, 5), colorsDict["wizardPurple"])
        imNew.putpixel((9, 5), colorsDict["wizardPurple"])
        imNew.putpixel((10, 5), colorsDict["wizardStar"])
        imNew.putpixel((11, 5), colorsDict["wizardPurple"])
        imNew.putpixel((12, 5), colorsDict["wizardPurple"])
        imNew.putpixel((13, 5), colorsDict["wizardPurple"])
        imNew.putpixel((14, 5), colorsDict["wizardPurple"])
        imNew.putpixel((15, 5), colorsDict["wizardPurple"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((17, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((18, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((19, 5), colorsDict["solanaBand"][5])

        imNew.putpixel((3, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((4, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((5, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((7, 6), colorsDict["wizardPurple"])
        imNew.putpixel((8, 6), colorsDict["wizardPurple"])
        imNew.putpixel((9, 6), colorsDict["wizardPurple"])
        imNew.putpixel((10, 6), colorsDict["wizardPurple"])
        imNew.putpixel((11, 6), colorsDict["wizardPurple"])
        imNew.putpixel((12, 6), colorsDict["wizardPurple"])
        imNew.putpixel((13, 6), colorsDict["wizardPurple"])
        imNew.putpixel((14, 6), colorsDict["wizardStar"])
        imNew.putpixel((15, 6), colorsDict["wizardPurple"])
        imNew.putpixel((16, 6), colorsDict["wizardPurpleShade"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["black"])
        imNew.putpixel((19, 6), colorsDict["black"])

        imNew.putpixel((3, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((4, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((5, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((6, 7), colorsDict["black"])
        imNew.putpixel((7, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((8, 7), colorsDict["wizardStar"])
        imNew.putpixel((9, 7), colorsDict["wizardPurple"])
        imNew.putpixel((10, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((11, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((12, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((13, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((14, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((15, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((16, 7), colorsDict["wizardPurpleShade"])
        imNew.putpixel((17, 7), colorsDict["wizardPurple"])
        imNew.putpixel((18, 7), colorsDict["wizardPurple"])
        imNew.putpixel((19, 7), colorsDict["wizardPurple"])
        imNew.putpixel((20, 7), colorsDict["black"])

        imNew.putpixel((3, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((4, 8), colorsDict["black"])
        imNew.putpixel((5, 8), colorsDict["black"])
        imNew.putpixel((6, 8), colorsDict["wizardPurple"])
        imNew.putpixel((7, 8), colorsDict["wizardPurpleShade"])
        imNew.putpixel((8, 8), colorsDict["wizardPurpleShade"])
        imNew.putpixel((9, 8), colorsDict["wizardPurpleShade"])
        imNew.putpixel((10, 8), colorsDict["wizardPurple"])
        imNew.putpixel((11, 8), colorsDict["wizardPurple"])
        imNew.putpixel((12, 8), colorsDict["wizardPurple"])
        imNew.putpixel((13, 8), colorsDict["wizardPurple"])
        imNew.putpixel((14, 8), colorsDict["wizardPurple"])
        imNew.putpixel((15, 8), colorsDict["wizardPurple"])
        imNew.putpixel((16, 8), colorsDict["wizardPurple"])
        imNew.putpixel((17, 8), colorsDict["black"])
        imNew.putpixel((18, 8), colorsDict["black"])
        imNew.putpixel((19, 8), colorsDict["black"])

        imNew.putpixel((3, 9), colorsDict["black"])
        imNew.putpixel((4, 9), colorsDict["wizardPurpleShade"])
        imNew.putpixel((5, 9), colorsDict["wizardPurpleShade"])
        imNew.putpixel((6, 9), colorsDict["wizardPurpleShade"])
        imNew.putpixel((7, 9), colorsDict["wizardPurple"])
        imNew.putpixel((8, 9), colorsDict["wizardPurple"])
        imNew.putpixel((9, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["black"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((13, 9), colorsDict["black"])
        imNew.putpixel((14, 9), colorsDict["black"])
        imNew.putpixel((15, 9), colorsDict["black"])
        imNew.putpixel((16, 9), colorsDict["black"])

        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])

    elif decodedType == "Crown":
        imNew.putpixel((11, 1), colorsDict["crownEdge"])
        imNew.putpixel((12, 1), colorsDict["crownEdge"])

        imNew.putpixel((6, 2), colorsDict["crownEdge"])
        imNew.putpixel((8, 2), colorsDict["crownEdge"])
        imNew.putpixel((10, 2), colorsDict["crownEdge"])
        imNew.putpixel((11, 2), colorsDict["crownShade1"])
        imNew.putpixel((12, 2), colorsDict["crownShade1"])
        imNew.putpixel((13, 2), colorsDict["crownEdge"])
        imNew.putpixel((15, 2), colorsDict["crownEdge"])
        imNew.putpixel((17, 2), colorsDict["crownEdge"])

        imNew.putpixel((5, 3), colorsDict["crownEdge"])
        imNew.putpixel((6, 3), colorsDict["crownShade4"])
        imNew.putpixel((7, 3), colorsDict["crownEdge"])
        imNew.putpixel((8, 3), colorsDict["crownShadow"])
        imNew.putpixel((9, 3), colorsDict["crownEdge"])
        imNew.putpixel((10, 3), colorsDict["crownShade1"])
        imNew.putpixel((11, 3), colorsDict["crownDiamond1"])
        imNew.putpixel((12, 3), colorsDict["crownDiamond2"])
        imNew.putpixel((13, 3), colorsDict["crownShade2"])
        imNew.putpixel((14, 3), colorsDict["crownEdge"])
        imNew.putpixel((15, 3), colorsDict["crownShadow"])
        imNew.putpixel((16, 3), colorsDict["crownEdge"])
        imNew.putpixel((17, 3), colorsDict["crownShade1"])
        imNew.putpixel((18, 3), colorsDict["crownEdge"])

        imNew.putpixel((5, 4), colorsDict["crownEdge"])
        imNew.putpixel((6, 4), colorsDict["crownShade4"])
        imNew.putpixel((7, 4), colorsDict["crownShade4"])
        imNew.putpixel((8, 4), colorsDict["crownEdge"])
        imNew.putpixel((9, 4), colorsDict["crownEdge"])
        imNew.putpixel((10, 4), colorsDict["crownEdge"])
        imNew.putpixel((11, 4), colorsDict["crownShade3"])
        imNew.putpixel((12, 4), colorsDict["crownShade3"])
        imNew.putpixel((13, 4), colorsDict["crownEdge"])
        imNew.putpixel((14, 4), colorsDict["crownEdge"])
        imNew.putpixel((15, 4), colorsDict["crownEdge"])
        imNew.putpixel((16, 4), colorsDict["crownShade1"])
        imNew.putpixel((17, 4), colorsDict["crownShade1"])
        imNew.putpixel((18, 4), colorsDict["crownEdge"])

        imNew.putpixel((3, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["crownEdge"])
        imNew.putpixel((6, 5), colorsDict["crownShade5"])
        imNew.putpixel((7, 5), colorsDict["crownShade4"])
        imNew.putpixel((8, 5), colorsDict["crownShade4"])
        imNew.putpixel((9, 5), colorsDict["crownShade4"])
        imNew.putpixel((10, 5), colorsDict["crownShade4"])
        imNew.putpixel((11, 5), colorsDict["crownShade4"])
        imNew.putpixel((12, 5), colorsDict["crownShade3"])
        imNew.putpixel((13, 5), colorsDict["crownShade3"])
        imNew.putpixel((14, 5), colorsDict["crownShade2"])
        imNew.putpixel((15, 5), colorsDict["crownShade2"])
        imNew.putpixel((16, 5), colorsDict["crownShade1"])
        imNew.putpixel((17, 5), colorsDict["crownShade1"])
        imNew.putpixel((18, 5), colorsDict["crownEdge"])
        imNew.putpixel((19, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((20, 5), colorsDict["solanaBand"][5])

        imNew.putpixel((3, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((4, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((5, 6), colorsDict["crownEdge"])
        imNew.putpixel((6, 6), colorsDict["crownRuby2"])
        imNew.putpixel((7, 6), colorsDict["crownRuby1"])
        imNew.putpixel((8, 6), colorsDict["crownShade4"])
        imNew.putpixel((9, 6), colorsDict["crownQuartz2"])
        imNew.putpixel((10, 6), colorsDict["crownQuartz1"])
        imNew.putpixel((11, 6), colorsDict["crownShade4"])
        imNew.putpixel((12, 6), colorsDict["crownEmerald2"])
        imNew.putpixel((13, 6), colorsDict["crownEmerald1"])
        imNew.putpixel((14, 6), colorsDict["crownShade3"])
        imNew.putpixel((15, 6), colorsDict["crownSapphire2"])
        imNew.putpixel((16, 6), colorsDict["crownSapphire1"])
        imNew.putpixel((17, 6), colorsDict["crownShade1"])
        imNew.putpixel((18, 6), colorsDict["crownEdge"])
        imNew.putpixel((19, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((20, 6), colorsDict["solanaBand"][6])

        imNew.putpixel((3, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((4, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((5, 7), colorsDict["crownEdge"])
        imNew.putpixel((6, 7), colorsDict["crownRuby3"])
        imNew.putpixel((7, 7), colorsDict["crownRuby2"])
        imNew.putpixel((8, 7), colorsDict["crownShade5"])
        imNew.putpixel((9, 7), colorsDict["crownQuartz3"])
        imNew.putpixel((10, 7), colorsDict["crownQuartz2"])
        imNew.putpixel((11, 7), colorsDict["crownShade4"])
        imNew.putpixel((12, 7), colorsDict["crownEmerald3"])
        imNew.putpixel((13, 7), colorsDict["crownEmerald2"])
        imNew.putpixel((14, 7), colorsDict["crownShade3"])
        imNew.putpixel((15, 7), colorsDict["crownSapphire3"])
        imNew.putpixel((16, 7), colorsDict["crownSapphire2"])
        imNew.putpixel((17, 7), colorsDict["crownShade2"])
        imNew.putpixel((18, 7), colorsDict["crownEdge"])
        imNew.putpixel((19, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((20, 7), colorsDict["solanaBand"][7])

        imNew.putpixel((3, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((4, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((5, 8), colorsDict["crownEdge"])
        imNew.putpixel((6, 8), colorsDict["crownShade5"])
        imNew.putpixel((7, 8), colorsDict["crownShade5"])
        imNew.putpixel((8, 8), colorsDict["crownShade5"])
        imNew.putpixel((9, 8), colorsDict["crownShade5"])
        imNew.putpixel((10, 8), colorsDict["crownShade4"])
        imNew.putpixel((11, 8), colorsDict["crownShade4"])
        imNew.putpixel((12, 8), colorsDict["crownShade4"])
        imNew.putpixel((13, 8), colorsDict["crownShade4"])
        imNew.putpixel((14, 8), colorsDict["crownShade4"])
        imNew.putpixel((15, 8), colorsDict["crownShade3"])
        imNew.putpixel((16, 8), colorsDict["crownShade3"])
        imNew.putpixel((17, 8), colorsDict["crownShade3"])
        imNew.putpixel((18, 8), colorsDict["crownEdge"])
        imNew.putpixel((19, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((20, 8), colorsDict["solanaBand"][8])

        imNew.putpixel((5, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((6, 9), colorsDict["crownEdge"])
        imNew.putpixel((7, 9), colorsDict["crownEdge"])
        imNew.putpixel((8, 9), colorsDict["crownEdge"])
        imNew.putpixel((9, 9), colorsDict["crownEdge"])
        imNew.putpixel((10, 9), colorsDict["crownEdge"])
        imNew.putpixel((11, 9), colorsDict["crownEdge"])
        imNew.putpixel((12, 9), colorsDict["crownEdge"])
        imNew.putpixel((13, 9), colorsDict["crownEdge"])
        imNew.putpixel((14, 9), colorsDict["crownEdge"])
        imNew.putpixel((15, 9), colorsDict["crownEdge"])
        imNew.putpixel((16, 9), colorsDict["crownEdge"])
        imNew.putpixel((17, 9), colorsDict["crownEdge"])
        imNew.putpixel((18, 9), colorsDict["solanaBand"][9])
    elif decodedType == "Fez":
        imNew.putpixel((10, 4), colorsDict["fezString"])
        imNew.putpixel((11, 4), colorsDict["fez"])
        imNew.putpixel((12, 4), colorsDict["fez"])

        imNew.putpixel((9, 5), colorsDict["fezString"])
        imNew.putpixel((10, 5), colorsDict["fezShade"])
        imNew.putpixel((11, 5), colorsDict["fez"])
        imNew.putpixel((12, 5), colorsDict["fez"])

        imNew.putpixel((10, 6), colorsDict["fezShade"])
        imNew.putpixel((11, 6), colorsDict["fez"])
        imNew.putpixel((12, 6), colorsDict["fez"])
    elif decodedType == "Jester Hat":
        imNew.putpixel((12, 0), colorsDict["black"])
        imNew.putpixel((13, 0), colorsDict["jesterHatRedShade"])
        imNew.putpixel((14, 0), colorsDict["jesterHatRed"])
        imNew.putpixel((15, 0), colorsDict["black"])
        imNew.putpixel((17, 0), colorsDict["black"])
        imNew.putpixel((18, 0), colorsDict["jesterHatYellow"])
        imNew.putpixel((19, 0), colorsDict["black"])

        imNew.putpixel((11, 1), colorsDict["black"])
        imNew.putpixel((12, 1), colorsDict["jesterHatRedShade"])
        imNew.putpixel((13, 1), colorsDict["jesterHatRed"])
        imNew.putpixel((14, 1), colorsDict["black"])
        imNew.putpixel((18, 1), colorsDict["black"])

        imNew.putpixel((7, 2), colorsDict["black"])
        imNew.putpixel((8, 2), colorsDict["black"])
        imNew.putpixel((9, 2), colorsDict["black"])
        imNew.putpixel((11, 2), colorsDict["black"])
        imNew.putpixel((12, 2), colorsDict["jesterHatRedShade"])
        imNew.putpixel((13, 2), colorsDict["jesterHatRed"])
        imNew.putpixel((14, 2), colorsDict["black"])

        imNew.putpixel((6, 3), colorsDict["black"])
        imNew.putpixel((7, 3), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((8, 3), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((9, 3), colorsDict["jesterHatGreen"])
        imNew.putpixel((10, 3), colorsDict["black"])
        imNew.putpixel((11, 3), colorsDict["black"])
        imNew.putpixel((12, 3), colorsDict["jesterHatRedShade"])
        imNew.putpixel((13, 3), colorsDict["jesterHatRed"])
        imNew.putpixel((14, 3), colorsDict["jesterHatRed"])
        imNew.putpixel((15, 3), colorsDict["black"])
        imNew.putpixel((16, 3), colorsDict["solanaBand"][3])
        imNew.putpixel((17, 3), colorsDict["solanaBand"][3])
        imNew.putpixel((18, 3), colorsDict["solanaBand"][3])
        imNew.putpixel((19, 3), colorsDict["solanaBand"][3])

        imNew.putpixel((5, 4), colorsDict["black"])
        imNew.putpixel((6, 4), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((7, 4), colorsDict["jesterHatGreen"])
        imNew.putpixel((8, 4), colorsDict["jesterHatGreen"])
        imNew.putpixel((9, 4), colorsDict["jesterHatGreen"])
        imNew.putpixel((10, 4), colorsDict["jesterHatGreen"])
        imNew.putpixel((11, 4), colorsDict["jesterHatGreen"])
        imNew.putpixel((12, 4), colorsDict["black"])
        imNew.putpixel((13, 4), colorsDict["black"])
        imNew.putpixel((14, 4), colorsDict["black"])
        imNew.putpixel((15, 4), colorsDict["jesterHatBlueShade"])
        imNew.putpixel((16, 4), colorsDict["black"])
        imNew.putpixel((17, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((18, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((19, 4), colorsDict["solanaBand"][4])

        imNew.putpixel((4, 5), colorsDict["black"])
        imNew.putpixel((5, 5), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((6, 5), colorsDict["jesterHatGreen"])
        imNew.putpixel((7, 5), colorsDict["black"])
        imNew.putpixel((8, 5), colorsDict["jesterHatGreen"])
        imNew.putpixel((9, 5), colorsDict["jesterHatGreen"])
        imNew.putpixel((10, 5), colorsDict["jesterHatGreen"])
        imNew.putpixel((11, 5), colorsDict["jesterHatGreen"])
        imNew.putpixel((12, 5), colorsDict["black"])
        imNew.putpixel((13, 5), colorsDict["jesterHatBlueShade"])
        imNew.putpixel((14, 5), colorsDict["jesterHatBlue"])
        imNew.putpixel((15, 5), colorsDict["jesterHatBlue"])
        imNew.putpixel((16, 5), colorsDict["jesterHatBlue"])
        imNew.putpixel((17, 5), colorsDict["black"])
        imNew.putpixel((18, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((19, 5), colorsDict["black"])

        imNew.putpixel((4, 6), colorsDict["black"])
        imNew.putpixel((5, 6), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((7, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((8, 6), colorsDict["black"])
        imNew.putpixel((9, 6), colorsDict["jesterHatGreenShade"])
        imNew.putpixel((10, 6), colorsDict["jesterHatGreen"])
        imNew.putpixel((11, 6), colorsDict["black"])
        imNew.putpixel((12, 6), colorsDict["jesterHatBlueShade"])
        imNew.putpixel((13, 6), colorsDict["jesterHatBlue"])
        imNew.putpixel((14, 6), colorsDict["jesterHatBlue"])
        imNew.putpixel((15, 6), colorsDict["jesterHatBlue"])
        imNew.putpixel((16, 6), colorsDict["black"])
        imNew.putpixel((17, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((18, 6), colorsDict["black"])
        imNew.putpixel((19, 6), colorsDict["jesterHatYellow"])
        imNew.putpixel((20, 6), colorsDict["black"])

        imNew.putpixel((4, 7), colorsDict["black"])
        imNew.putpixel((5, 7), colorsDict["black"])
        imNew.putpixel((6, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((7, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((8, 7), colorsDict["black"])
        imNew.putpixel((9, 7), colorsDict["black"])
        imNew.putpixel((10, 7), colorsDict["black"])
        imNew.putpixel((11, 7), colorsDict["black"])
        imNew.putpixel((12, 7), colorsDict["black"])
        imNew.putpixel((13, 7), colorsDict["black"])
        imNew.putpixel((14, 7), colorsDict["black"])
        imNew.putpixel((15, 7), colorsDict["black"])
        imNew.putpixel((16, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((17, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((18, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((19, 7), colorsDict["black"])

        imNew.putpixel((3, 8), colorsDict["black"])
        imNew.putpixel((4, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((5, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((6, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((7, 8), colorsDict["black"])
        imNew.putpixel((8, 8), colorsDict["jesterHatYellowShade"])
        imNew.putpixel((9, 8), colorsDict["jesterHatYellowShade"])
        imNew.putpixel((10, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((11, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((12, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((13, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((14, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((15, 8), colorsDict["jesterHatYellow"])
        imNew.putpixel((16, 8), colorsDict["black"])
        imNew.putpixel((17, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((18, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((19, 8), colorsDict["solanaBand"][8])

        imNew.putpixel((2, 9), colorsDict["black"])
        imNew.putpixel((3, 9), colorsDict["jesterHatYellow"])
        imNew.putpixel((4, 9), colorsDict["black"])
        imNew.putpixel((5, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((6, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((8, 9), colorsDict["black"])
        imNew.putpixel((9, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["black"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((13, 9), colorsDict["black"])
        imNew.putpixel((14, 9), colorsDict["black"])
        imNew.putpixel((15, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((18, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((19, 9), colorsDict["solanaBand"][9])

        imNew.putpixel((3, 10), colorsDict["black"])
    
    elif decodedType == "Beer Hat" :
        imNew.putpixel((6, 2), colorsDict["beerCanTubeShade"])
        imNew.putpixel((7, 2), colorsDict["beerCanTubeShade"])
        imNew.putpixel((8, 2), colorsDict["beerCanTube"])
        imNew.putpixel((9, 2), colorsDict["beerCanTube"])
        imNew.putpixel((10, 2), colorsDict["beerCanTube"])
        imNew.putpixel((11, 2), colorsDict["beerCanTube"])
        imNew.putpixel((12, 2), colorsDict["beerCanTube"])
        imNew.putpixel((13, 2), colorsDict["beerCanTube"])
        imNew.putpixel((14, 2), colorsDict["beerCanTube"])
        imNew.putpixel((15, 2), colorsDict["beerCanTube"])
        imNew.putpixel((16, 2), colorsDict["beerCanTube"])
        imNew.putpixel((17, 2), colorsDict["beerCanTube"])

        imNew.putpixel((4, 3), colorsDict["beerCanTubeShade"])
        imNew.putpixel((5, 3), colorsDict["beerCanTube"])
        imNew.putpixel((8, 3), colorsDict["black"])
        imNew.putpixel((9, 3), colorsDict["black"])
        imNew.putpixel((10, 3), colorsDict["black"])
        imNew.putpixel((11, 3), colorsDict["black"])
        imNew.putpixel((12, 3), colorsDict["black"])
        imNew.putpixel((13, 3), colorsDict["black"])
        imNew.putpixel((14, 3), colorsDict["black"])
        imNew.putpixel((15, 3), colorsDict["black"])
        imNew.putpixel((18, 3), colorsDict["beerCanTube"])
        imNew.putpixel((19, 3), colorsDict["beerCanTubeShade"])

        imNew.putpixel((2, 4), colorsDict["beerCanTubeShade"])
        imNew.putpixel((3, 4), colorsDict["beerCanTube"])
        imNew.putpixel((5, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((6, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((7, 4), colorsDict["black"])
        imNew.putpixel((8, 4), colorsDict["black"])
        imNew.putpixel((9, 4), colorsDict["beerHatShade"])
        imNew.putpixel((10, 4), colorsDict["beerHat"])
        imNew.putpixel((11, 4), colorsDict["beerHat"])
        imNew.putpixel((12, 4), colorsDict["beerHat"])
        imNew.putpixel((13, 4), colorsDict["beerHat"])
        imNew.putpixel((14, 4), colorsDict["beerHat"])
        imNew.putpixel((15, 4), colorsDict["black"])
        imNew.putpixel((16, 4), colorsDict["black"])
        imNew.putpixel((17, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((18, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((19, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((20, 4), colorsDict["beerCanTube"])
        imNew.putpixel((21, 4), colorsDict["beerCanTubeShade"])

        imNew.putpixel((2, 5), colorsDict["beerCanTube"])
        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((6, 5), colorsDict["black"])
        imNew.putpixel((7, 5), colorsDict["black"])
        imNew.putpixel((8, 5), colorsDict["beerHatShade"])
        imNew.putpixel((9, 5), colorsDict["beerHat"])
        imNew.putpixel((10, 5), colorsDict["beerHat"])
        imNew.putpixel((11, 5), colorsDict["beerHat"])
        imNew.putpixel((12, 5), colorsDict["beerHat"])
        imNew.putpixel((13, 5), colorsDict["beerHat"])
        imNew.putpixel((14, 5), colorsDict["beerHat"])
        imNew.putpixel((15, 5), colorsDict["beerHat"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((17, 5), colorsDict["black"])
        imNew.putpixel((18, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((19, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((20, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((21, 5), colorsDict["beerCanTube"])


        imNew.putpixel((1, 6), colorsDict["beerCanShade"])
        imNew.putpixel((2, 6), colorsDict["beerCan"])
        imNew.putpixel((3, 6), colorsDict["beerCan"])
        imNew.putpixel((4, 6), colorsDict["black"])
        imNew.putpixel((5, 6), colorsDict["black"])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((7, 6), colorsDict["beerHatShade"])
        imNew.putpixel((8, 6), colorsDict["beerHat"])
        imNew.putpixel((9, 6), colorsDict["beerHat"])
        imNew.putpixel((10, 6), colorsDict["beerHat"])
        imNew.putpixel((11, 6), colorsDict["beerHat"])
        imNew.putpixel((12, 6), colorsDict["beerHat"])
        imNew.putpixel((13, 6), colorsDict["beerHat"])
        imNew.putpixel((14, 6), colorsDict["beerHat"])
        imNew.putpixel((15, 6), colorsDict["beerHat"])
        imNew.putpixel((16, 6), colorsDict["beerHat"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["black"])
        imNew.putpixel((19, 6), colorsDict["black"])
        imNew.putpixel((20, 6), colorsDict["beerCanShade"])
        imNew.putpixel((21, 6), colorsDict["beerCan"])
        imNew.putpixel((22, 6), colorsDict["beerCan"])

        imNew.putpixel((1, 7), colorsDict["beerCanShade"])
        imNew.putpixel((2, 7), colorsDict["beerCan"])
        imNew.putpixel((3, 7), colorsDict["beerCan"])
        imNew.putpixel((4, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((5, 7), colorsDict["black"])
        imNew.putpixel((6, 7), colorsDict["black"])
        imNew.putpixel((7, 7), colorsDict["beerHatShade"])
        imNew.putpixel((8, 7), colorsDict["beerHat"])
        imNew.putpixel((9, 7), colorsDict["beerHat"])
        imNew.putpixel((10, 7), colorsDict["beerHat"])
        imNew.putpixel((11, 7), colorsDict["beerHat"])
        imNew.putpixel((12, 7), colorsDict["beerHat"])
        imNew.putpixel((13, 7), colorsDict["beerHat"])
        imNew.putpixel((14, 7), colorsDict["beerHat"])
        imNew.putpixel((15, 7), colorsDict["beerHat"])
        imNew.putpixel((16, 7), colorsDict["beerHat"])
        imNew.putpixel((17, 7), colorsDict["black"])
        imNew.putpixel((18, 7), colorsDict["black"])
        imNew.putpixel((19, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((20, 7), colorsDict["beerCanShade"])
        imNew.putpixel((21, 7), colorsDict["beerCan"])
        imNew.putpixel((22, 7), colorsDict["beerCan"])

        imNew.putpixel((1, 8), colorsDict["black"])
        imNew.putpixel((2, 8), colorsDict["black"])
        imNew.putpixel((3, 8), colorsDict["black"])
        imNew.putpixel((4, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((5, 8), colorsDict["black"])
        imNew.putpixel((6, 8), colorsDict["beerHatShade"])
        imNew.putpixel((7, 8), colorsDict["beerHat"])
        imNew.putpixel((8, 8), colorsDict["beerHat"])
        imNew.putpixel((9, 8), colorsDict["beerHat"])
        imNew.putpixel((10, 8), colorsDict["beerHat"])
        imNew.putpixel((11, 8), colorsDict["beerHat"])
        imNew.putpixel((12, 8), colorsDict["beerHat"])
        imNew.putpixel((13, 8), colorsDict["beerHat"])
        imNew.putpixel((14, 8), colorsDict["beerHat"])
        imNew.putpixel((15, 8), colorsDict["beerHat"])
        imNew.putpixel((16, 8), colorsDict["beerHat"])
        imNew.putpixel((17, 8), colorsDict["beerHat"])
        imNew.putpixel((18, 8), colorsDict["black"])
        imNew.putpixel((19, 8), colorsDict["solanaBand"][8])
        imNew.putpixel((20, 8), colorsDict["black"])
        imNew.putpixel((21, 8), colorsDict["black"])
        imNew.putpixel((22, 8), colorsDict["black"])

        imNew.putpixel((1, 9), colorsDict["beerCanShade"])
        imNew.putpixel((2, 9), colorsDict["beerCan"])
        imNew.putpixel((3, 9), colorsDict["beerCan"])
        imNew.putpixel((4, 9), colorsDict["solanaBand"][9])
        imNew.putpixel((5, 9), colorsDict["black"])
        imNew.putpixel((6, 9), colorsDict["black"])
        imNew.putpixel((7, 9), colorsDict["black"])
        imNew.putpixel((8, 9), colorsDict["black"])
        imNew.putpixel((9, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["black"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((13, 9), colorsDict["black"])
        imNew.putpixel((14, 9), colorsDict["black"])
        imNew.putpixel((15, 9), colorsDict["black"])
        imNew.putpixel((16, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["black"])
        imNew.putpixel((18, 9), colorsDict["black"])
        imNew.putpixel((20, 9), colorsDict["beerCanShade"])
        imNew.putpixel((21, 9), colorsDict["beerCan"])
        imNew.putpixel((22, 9), colorsDict["beerCan"])

        imNew.putpixel((1, 10), colorsDict["beerCanShade"])
        imNew.putpixel((2, 10), colorsDict["beerCan"])
        imNew.putpixel((3, 10), colorsDict["beerCan"])
        imNew.putpixel((20, 10), colorsDict["beerCanShade"])
        imNew.putpixel((21, 10), colorsDict["beerCan"])
        imNew.putpixel((22, 10), colorsDict["beerCan"])

    elif decodedType == "Santa Hat" :
        imNew.putpixel((3, 1), colorsDict["black"])
        imNew.putpixel((4, 1), colorsDict["black"])
        imNew.putpixel((6, 1), colorsDict["black"])
        imNew.putpixel((7, 1), colorsDict["black"])
        imNew.putpixel((8, 1), colorsDict["black"])
        imNew.putpixel((9, 1), colorsDict["black"])
        
        imNew.putpixel((2, 2), colorsDict["black"])
        imNew.putpixel((3, 2), colorsDict["white"])
        imNew.putpixel((4, 2), colorsDict["white"])
        imNew.putpixel((5, 2), colorsDict["black"])
        imNew.putpixel((6, 2), colorsDict["beerHatShade"])
        imNew.putpixel((7, 2), colorsDict["beerHat"])
        imNew.putpixel((8, 2), colorsDict["beerHat"])
        imNew.putpixel((9, 2), colorsDict["beerHat"])
        imNew.putpixel((10, 2), colorsDict["black"])
        imNew.putpixel((11, 2), colorsDict["black"])

        imNew.putpixel((2, 3), colorsDict["black"])
        imNew.putpixel((3, 3), colorsDict["santaHatWhiteShade"])
        imNew.putpixel((4, 3), colorsDict["white"])
        imNew.putpixel((5, 3), colorsDict["black"])
        imNew.putpixel((6, 3), colorsDict["beerHatShade"])
        imNew.putpixel((7, 3), colorsDict["beerHatShade"])
        imNew.putpixel((8, 3), colorsDict["beerHat"])
        imNew.putpixel((9, 3), colorsDict["beerHat"])
        imNew.putpixel((10, 3), colorsDict["beerHat"])
        imNew.putpixel((11, 3), colorsDict["beerHat"])
        imNew.putpixel((12, 3), colorsDict["black"])
        imNew.putpixel((13, 3), colorsDict["black"])

        imNew.putpixel((3, 4), colorsDict["black"])
        imNew.putpixel((4, 4), colorsDict["black"])
        imNew.putpixel((5, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((6, 4), colorsDict["black"])
        imNew.putpixel((7, 4), colorsDict["black"])
        imNew.putpixel((8, 4), colorsDict["beerHatShade"])
        imNew.putpixel((9, 4), colorsDict["beerHat"])
        imNew.putpixel((10, 4), colorsDict["beerHat"])
        imNew.putpixel((11, 4), colorsDict["beerHat"])
        imNew.putpixel((12, 4), colorsDict["beerHat"])
        imNew.putpixel((13, 4), colorsDict["beerHat"])
        imNew.putpixel((14, 4), colorsDict["black"])
        imNew.putpixel((15, 4), colorsDict["black"])
        imNew.putpixel((16, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((17, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((18, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((19, 4), colorsDict["solanaBand"][4])

        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((6, 5), colorsDict["black"])
        imNew.putpixel((7, 5), colorsDict["black"])
        imNew.putpixel((8, 5), colorsDict["beerHatShade"])
        imNew.putpixel((9, 5), colorsDict["beerHat"])
        imNew.putpixel((10, 5), colorsDict["beerHat"])
        imNew.putpixel((11, 5), colorsDict["beerHat"])
        imNew.putpixel((12, 5), colorsDict["beerHat"])
        imNew.putpixel((13, 5), colorsDict["beerHat"])
        imNew.putpixel((14, 5), colorsDict["beerHat"])
        imNew.putpixel((15, 5), colorsDict["beerHat"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((18, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((19, 5), colorsDict["solanaBand"][5])

        imNew.putpixel((4, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((5, 6), colorsDict["black"])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((7, 6), colorsDict["black"])
        imNew.putpixel((8, 6), colorsDict["black"])
        imNew.putpixel((9, 6), colorsDict["black"])
        imNew.putpixel((10, 6), colorsDict["black"])
        imNew.putpixel((11, 6), colorsDict["black"])
        imNew.putpixel((12, 6), colorsDict["black"])
        imNew.putpixel((13, 6), colorsDict["black"])
        imNew.putpixel((14, 6), colorsDict["black"])
        imNew.putpixel((15, 6), colorsDict["black"])
        imNew.putpixel((16, 6), colorsDict["black"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["black"])
        imNew.putpixel((19, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((19, 6), colorsDict["solanaBand"][6])

        imNew.putpixel((4, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((5, 7), colorsDict["black"])
        imNew.putpixel((6, 7), colorsDict["black"])
        imNew.putpixel((7, 7), colorsDict["santaHatWhiteShade"])
        imNew.putpixel((8, 7), colorsDict["white"])
        imNew.putpixel((9, 7), colorsDict["white"])
        imNew.putpixel((10, 7), colorsDict["white"])
        imNew.putpixel((11, 7), colorsDict["white"])
        imNew.putpixel((12, 7), colorsDict["white"])
        imNew.putpixel((13, 7), colorsDict["white"])
        imNew.putpixel((14, 7), colorsDict["white"])
        imNew.putpixel((15, 7), colorsDict["white"])
        imNew.putpixel((16, 7), colorsDict["white"])
        imNew.putpixel((17, 7), colorsDict["black"])
        imNew.putpixel((18, 7), colorsDict["black"])
        imNew.putpixel((19, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((19, 7), colorsDict["solanaBand"][7])

        

        imNew.putpixel((5, 8), colorsDict["black"])
        imNew.putpixel((6, 8), colorsDict["santaHatWhiteShade"])
        imNew.putpixel((7, 8), colorsDict["white"])
        imNew.putpixel((8, 8), colorsDict["white"])
        imNew.putpixel((9, 8), colorsDict["white"])
        imNew.putpixel((10, 8), colorsDict["white"])
        imNew.putpixel((11, 8), colorsDict["white"])
        imNew.putpixel((12, 8), colorsDict["white"])
        imNew.putpixel((13, 8), colorsDict["white"])
        imNew.putpixel((14, 8), colorsDict["white"])
        imNew.putpixel((15, 8), colorsDict["white"])
        imNew.putpixel((16, 8), colorsDict["white"])
        imNew.putpixel((17, 8), colorsDict["white"])
        imNew.putpixel((18, 8), colorsDict["black"])

        imNew.putpixel((5, 9), colorsDict["black"])
        imNew.putpixel((6, 9), colorsDict["black"])
        imNew.putpixel((7, 9), colorsDict["black"])
        imNew.putpixel((8, 9), colorsDict["black"])
        imNew.putpixel((9, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["black"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((13, 9), colorsDict["black"])
        imNew.putpixel((14, 9), colorsDict["black"])
        imNew.putpixel((15, 9), colorsDict["black"])
        imNew.putpixel((16, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["black"])
        imNew.putpixel((18, 9), colorsDict["black"])

    elif decodedType == "Sombrero" :
        imNew.putpixel((11, 1), colorsDict["black"])
        imNew.putpixel((12, 1), colorsDict["black"])

        imNew.putpixel((10, 2), colorsDict["black"])
        imNew.putpixel((11, 2), colorsDict["sombreroShade"])
        imNew.putpixel((12, 2), colorsDict["sombrero"])
        imNew.putpixel((13, 2), colorsDict["black"])
        
        imNew.putpixel((9, 3), colorsDict["black"])
        imNew.putpixel((10, 3), colorsDict["sombreroShade"])
        imNew.putpixel((11, 3), colorsDict["sombrero"])
        imNew.putpixel((12, 3), colorsDict["sombrero"])
        imNew.putpixel((13, 3), colorsDict["sombrero"])
        imNew.putpixel((14, 3), colorsDict["black"])

        imNew.putpixel((5, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((6, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((9, 4), colorsDict["black"])
        imNew.putpixel((10, 4), colorsDict["sombreroShade"])
        imNew.putpixel((11, 4), colorsDict["sombrero"])
        imNew.putpixel((12, 4), colorsDict["sombrero"])
        imNew.putpixel((13, 4), colorsDict["sombrero"])
        imNew.putpixel((14, 4), colorsDict["black"])
        imNew.putpixel((17, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((18, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((19, 4), colorsDict["solanaBand"][4])
       
        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((6, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((7, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((9, 5), colorsDict["black"])
        imNew.putpixel((10, 5), colorsDict["sombreroShade"])
        imNew.putpixel((11, 5), colorsDict["sombrero"])
        imNew.putpixel((12, 5), colorsDict["sombrero"])
        imNew.putpixel((13, 5), colorsDict["sombrero"])
        imNew.putpixel((14, 5), colorsDict["black"])
        imNew.putpixel((17, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((18, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((19, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((20, 5), colorsDict["solanaBand"][5])

        imNew.putpixel((1, 6), colorsDict["black"])
        imNew.putpixel((2, 6), colorsDict["black"])
        imNew.putpixel((3, 6), colorsDict["black"])
        imNew.putpixel((4, 6), colorsDict["black"])
        imNew.putpixel((5, 6), colorsDict["black"])
        imNew.putpixel((6, 6), colorsDict["black"])
        imNew.putpixel((7, 6), colorsDict["black"])
        imNew.putpixel((8, 6), colorsDict["black"])
        imNew.putpixel((9, 6), colorsDict["black"])
        imNew.putpixel((10, 6), colorsDict["black"])
        imNew.putpixel((11, 6), colorsDict["black"])
        imNew.putpixel((12, 6), colorsDict["black"])
        imNew.putpixel((13, 6), colorsDict["black"])
        imNew.putpixel((14, 6), colorsDict["black"])
        imNew.putpixel((15, 6), colorsDict["black"])
        imNew.putpixel((16, 6), colorsDict["black"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["black"])
        imNew.putpixel((19, 6), colorsDict["black"])
        imNew.putpixel((20, 6), colorsDict["black"])
        imNew.putpixel((21, 6), colorsDict["black"])
        imNew.putpixel((22, 6), colorsDict["black"])

        imNew.putpixel((1, 7), colorsDict["black"])
        imNew.putpixel((2, 7), colorsDict["sombreroYellowShade"])
        imNew.putpixel((3, 7), colorsDict["sombreroShade"])
        imNew.putpixel((4, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((5, 7), colorsDict["sombrero"])
        imNew.putpixel((6, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((7, 7), colorsDict["sombrero"])
        imNew.putpixel((8, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((9, 7), colorsDict["sombrero"])
        imNew.putpixel((10, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((11, 7), colorsDict["sombrero"])
        imNew.putpixel((12, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((13, 7), colorsDict["sombrero"])
        imNew.putpixel((14, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((15, 7), colorsDict["sombrero"])
        imNew.putpixel((16, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((17, 7), colorsDict["sombrero"])
        imNew.putpixel((18, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((19, 7), colorsDict["sombrero"])
        imNew.putpixel((20, 7), colorsDict["sombreroYellow"])
        imNew.putpixel((21, 7), colorsDict["sombrero"])
        imNew.putpixel((22, 7), colorsDict["black"])

        imNew.putpixel((2, 8), colorsDict["black"])
        imNew.putpixel((3, 8), colorsDict["sombreroBlueShade"])
        imNew.putpixel((4, 8), colorsDict["sombreroShade"])
        imNew.putpixel((5, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((6, 8), colorsDict["sombrero"])
        imNew.putpixel((7, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((8, 8), colorsDict["sombrero"])
        imNew.putpixel((9, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((10, 8), colorsDict["sombrero"])
        imNew.putpixel((11, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((12, 8), colorsDict["sombrero"])
        imNew.putpixel((13, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((14, 8), colorsDict["sombrero"])
        imNew.putpixel((15, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((16, 8), colorsDict["sombrero"])
        imNew.putpixel((17, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((18, 8), colorsDict["sombrero"])
        imNew.putpixel((19, 8), colorsDict["sombreroBlue"])
        imNew.putpixel((20, 8), colorsDict["sombrero"])
        imNew.putpixel((21, 8), colorsDict["black"])

        imNew.putpixel((3, 9), colorsDict["black"])
        imNew.putpixel((4, 9), colorsDict["beerHatShade"])
        imNew.putpixel((5, 9), colorsDict["sombreroShade"])
        imNew.putpixel((6, 9), colorsDict["sombreroRed"])
        imNew.putpixel((7, 9), colorsDict["sombrero"])
        imNew.putpixel((8, 9), colorsDict["sombreroRed"])
        imNew.putpixel((9, 9), colorsDict["sombrero"])
        imNew.putpixel((10, 9), colorsDict["sombreroRed"])
        imNew.putpixel((11, 9), colorsDict["sombrero"])
        imNew.putpixel((12, 9), colorsDict["sombreroRed"])
        imNew.putpixel((13, 9), colorsDict["sombrero"])
        imNew.putpixel((14, 9), colorsDict["sombreroRed"])
        imNew.putpixel((15, 9), colorsDict["sombrero"])
        imNew.putpixel((16, 9), colorsDict["sombreroRed"])
        imNew.putpixel((17, 9), colorsDict["sombrero"])
        imNew.putpixel((18, 9), colorsDict["sombreroRed"])
        imNew.putpixel((19, 9), colorsDict["sombrero"])
        imNew.putpixel((20, 9), colorsDict["black"])
       
        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])
        imNew.putpixel((18, 10), colorsDict["black"])
        imNew.putpixel((19, 10), colorsDict["black"])

    elif decodedType == "Goku Hair":
        imNew.putpixel((11, 0), colorsDict["black"])
        imNew.putpixel((12, 0), colorsDict["gokuHairShade"])
        imNew.putpixel((13, 0), colorsDict["gokuHairShade"])
        imNew.putpixel((14, 0), colorsDict["black"])

        imNew.putpixel((10, 1), colorsDict["black"])
        imNew.putpixel((11, 1), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 1), colorsDict["gokuHairShade"])
        imNew.putpixel((13, 1), colorsDict["black"])

        imNew.putpixel((9, 2), colorsDict["black"])
        imNew.putpixel((10, 2), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 2), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 2), colorsDict["black"])
        imNew.putpixel((13, 2), colorsDict["black"])
        imNew.putpixel((16, 2), colorsDict["black"])
        imNew.putpixel((17, 2), colorsDict["black"])

        imNew.putpixel((8, 3), colorsDict["black"])
        imNew.putpixel((9, 3), colorsDict["gokuHairShade"])
        imNew.putpixel((10, 3), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 3), colorsDict["black"])
        imNew.putpixel((12, 3), colorsDict["black"])
        imNew.putpixel((15, 3), colorsDict["black"])
        imNew.putpixel((16, 3), colorsDict["gokuHairShade"])
        imNew.putpixel((17, 3), colorsDict["gokuHairShade"])
        imNew.putpixel((18, 3), colorsDict["black"])

        imNew.putpixel((5, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((6, 4), colorsDict["solanaBand"][4])
        imNew.putpixel((8, 4), colorsDict["black"])
        imNew.putpixel((9, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((10, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 4), colorsDict["black"])
        imNew.putpixel((12, 4), colorsDict["black"])
        imNew.putpixel((14, 4), colorsDict["black"])
        imNew.putpixel((15, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((16, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((17, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((18, 4), colorsDict["gokuHairShade"])
        imNew.putpixel((19, 4), colorsDict["black"])

        imNew.putpixel((4, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((5, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((6, 5), colorsDict["solanaBand"][5])
        imNew.putpixel((8, 5), colorsDict["black"])
        imNew.putpixel((9, 5), colorsDict["gokuHairShade"])
        imNew.putpixel((10, 5), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 5), colorsDict["black"])
        imNew.putpixel((12, 5), colorsDict["black"])
        imNew.putpixel((13, 5), colorsDict["black"])
        imNew.putpixel((14, 5), colorsDict["gokuHairShade"])
        imNew.putpixel((15, 5), colorsDict["gokuHairShade"])
        imNew.putpixel((16, 5), colorsDict["black"])
        imNew.putpixel((17, 5), colorsDict["black"])
        imNew.putpixel((18, 5), colorsDict["black"])
        imNew.putpixel((19, 5), colorsDict["black"])
        imNew.putpixel((20, 5), colorsDict["black"])

        imNew.putpixel((4, 6), colorsDict["black"])
        imNew.putpixel((5, 6), colorsDict["black"])
        imNew.putpixel((6, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((7, 6), colorsDict["black"])
        imNew.putpixel((8, 6), colorsDict["black"])
        imNew.putpixel((9, 6), colorsDict["black"])
        imNew.putpixel((10, 6), colorsDict["black"])
        imNew.putpixel((11, 6), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 6), colorsDict["black"])
        imNew.putpixel((13, 6), colorsDict["black"])
        imNew.putpixel((14, 6), colorsDict["gokuHairShade"])
        imNew.putpixel((15, 6), colorsDict["black"])
        imNew.putpixel((16, 6), colorsDict["black"])
        imNew.putpixel((17, 6), colorsDict["black"])
        imNew.putpixel((18, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((19, 6), colorsDict["solanaBand"][6])
        imNew.putpixel((20, 6), colorsDict["solanaBand"][6])

        imNew.putpixel((4, 7), colorsDict["solanaBand"][6])
        imNew.putpixel((5, 7), colorsDict["solanaBand"][6])
        imNew.putpixel((6, 7), colorsDict["black"])
        imNew.putpixel((7, 7), colorsDict["gokuHairShade"])
        imNew.putpixel((8, 7), colorsDict["gokuHairShade"])
        imNew.putpixel((9, 7), colorsDict["black"])
        imNew.putpixel((10, 7), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 7), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 7), colorsDict["black"])
        imNew.putpixel((13, 7), colorsDict["black"])
        imNew.putpixel((14, 7), colorsDict["black"])
        imNew.putpixel((15, 7), colorsDict["black"])
        imNew.putpixel((16, 7), colorsDict["black"])
        imNew.putpixel((17, 7), colorsDict["black"])
        imNew.putpixel((18, 7), colorsDict["black"])
        imNew.putpixel((19, 7), colorsDict["solanaBand"][7])
        imNew.putpixel((20, 7), colorsDict["solanaBand"][7])

        imNew.putpixel((4, 8), colorsDict["black"])
        imNew.putpixel((5, 8), colorsDict["black"])
        imNew.putpixel((6, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((7, 8), colorsDict["black"])
        imNew.putpixel((8, 8), colorsDict["black"])
        imNew.putpixel((9, 8), colorsDict["black"])
        imNew.putpixel((10, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((11, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 8), colorsDict["black"])
        imNew.putpixel((14, 8), colorsDict["black"])
        imNew.putpixel((15, 8), colorsDict["black"])
        imNew.putpixel((16, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((17, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((18, 8), colorsDict["gokuHairShade"])
        imNew.putpixel((19, 8), colorsDict["black"])
        imNew.putpixel((20, 8), colorsDict["solanaBand"][8])

        imNew.putpixel((2, 9), colorsDict["black"])
        imNew.putpixel((3, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((4, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((5, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((6, 9), colorsDict["black"])
        imNew.putpixel((7, 9), colorsDict["black"])
        imNew.putpixel((10, 9), colorsDict["black"])
        imNew.putpixel((11, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((12, 9), colorsDict["black"])
        imNew.putpixel((16, 9), colorsDict["black"])
        imNew.putpixel((17, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((18, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((19, 9), colorsDict["gokuHairShade"])
        imNew.putpixel((20, 9), colorsDict["black"])
        imNew.putpixel((21, 9), colorsDict["black"])

        imNew.putpixel((3, 10), colorsDict["black"])
        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])
        imNew.putpixel((18, 10), colorsDict["black"])
        imNew.putpixel((19, 10), colorsDict["black"])
        imNew.putpixel((20, 10), colorsDict["black"])
        imNew.putpixel((21, 10), colorsDict["black"])
        imNew.putpixel((22, 10), colorsDict["black"])


    im.paste(imNew, (0,0), mask=imNew)
